# .air.toml
root = "."
tmp_dir = "tmp"


[build]
cmd = "go build -o ./tmp/main ./main.go" #On windows add .exe to main
bin = "./tmp/main" #On windows add .exe to main
include_ext = ["go"]  # Only watch .go files
exclude_dir = ["tmp", "vendor", "node_modules", "public"]
delay = 1000  # ms
poll = true   # <-- important
[log]
time = true

[misc]
clean_on_exit = true