# Dockerfile.dev (Debian)
FROM golang:1.25

WORKDIR /app

# Installer bash, git et client PostgreSQL
RUN apt-get update && apt-get install -y bash git postgresql-client && rm -rf /var/lib/apt/lists/*

# Installer bash, git et client PostgreSQL
RUN apt-get update && apt-get install -y bash git postgresql-client && rm -rf /var/lib/apt/lists/*

# Installer Air
RUN go install github.com/air-verse/air@latest

# Installer Goose CLI
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

# Copier les fichiers de modules et télécharger les dépendances
COPY go.mod go.sum ./
RUN go mod download

# Copier le reste du code
COPY . .

# Exposer le port de l'app
EXPOSE 8080

COPY ./entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT ["/app/entrypoint.sh"]
# Lancer Air
CMD ["air", "-c", ".air.toml"]